name: dry-rails
custom_ci: true
codacy_id: d4677ea0c4c2497bb1af1b3ac31552f4
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "The official dry-rb railtie for Ruby on Rails"
  description: "dry-rails provides the official integration of dry-rb gems with Ruby on Rails framework."
  files: []
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [dry-system, "~> 0.18"]
    - [dry-schema, "~> 1.5"]
    - [dry-validation, "~> 1.5"]
